import profileJson from "@/data/profile.json";
import projectsJson from "@/data/projects.json";

export type Skill = {
  name: string;
  /** Proficiency 1–5, rendered as filled/unfilled pinout dots. */
  level: number;
};

export type SkillGroup = {
  group: string;
  note: string;
  items: Skill[];
};

export type Education = {
  school: string;
  degree: string;
  location: string;
  period: string;
  current: boolean;
  coursework: string[];
};

export type Social = {
  label: string;
  handle: string;
  url: string;
};

export type Profile = {
  name: string;
  initials: string;
  role: string;
  tagline: string;
  headline: string;
  summary: string;
  availability: string;
  location: string;
  email: string;
  phone: string;
  resumeUrl: string;
  /** 4:5 portrait in /public. Replace the placeholder with a real photo. */
  portraitUrl: string;
  about: string[];
  stats: { label: string; value: string }[];
  skillGroups: SkillGroup[];
  education: Education[];
  certifications: { name: string; issuer: string }[];
  languages: string[];
  workAuthorization: string;
  social: Social[];
  seo: {
    siteUrl: string;
    /** ISO date the site copy last changed — drives sitemap lastModified. */
    contentUpdated: string;
    title: string;
    description: string;
    keywords: string[];
    ogImage: string;
  };
};

export type ProjectSection = {
  heading: string;
  body: string;
};

export type Project = {
  slug: string;
  title: string;
  subtitle: string;
  category: string;
  context: string;
  year: string;
  /** ISO date this project's copy last changed — drives sitemap lastModified. */
  updated: string;
  featured: boolean;
  summary: string;
  /** 16:9 cover art in /public/projects, generated by scripts/generate-images.py */
  cover: string;
  coverAlt: string;
  stack: string[];
  metrics: { label: string; value: string }[];
  highlights: string[];
  sections: ProjectSection[];
  links: { label: string; url: string }[];
};

export const profile = profileJson as Profile;
export const projects = projectsJson as Project[];

export const featuredProjects = projects.filter((p) => p.featured);

export function getProject(slug: string): Project | undefined {
  return projects.find((p) => p.slug === slug);
}

/**
 * Canonical origin. Prefers the env var so preview deploys and local dev
 * generate correct absolute URLs, falling back to the value in profile.json.
 */
export const siteUrl = (
  process.env.NEXT_PUBLIC_SITE_URL || profile.seo.siteUrl
).replace(/\/$/, "");
